# Generated by Django 6.0.2 on 2026-02-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the prayer request has been approved by an admin'),
        ),
    ]
