# Generated by Django 6.0.2 on 2026-02-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_anonymoususer_alter_user_options_remove_user_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
