# Generated by Django 6.0.2 on 2026-02-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_anonymoususer_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
