# Generated by Qodo Command

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_uuid_anonymoususer_id_rename_uuid_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verfied",
            new_name="is_verified",
        ),
    ]
