# Generated by Qodo Command

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_is_verfied_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymoususer",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anonymoususer",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
