# Generated by Django 6.0.2 on 2026-02-23 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_anonymoususer_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('anonymous_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.anonymoususer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
